#!/bin/bash
ip=`ifconfig eth0 | grep 'inet addr' | awk {'print $2'} | sed s/.*://`
echo "######################################"
echo "Ubuntu GUI Desktop Installer with VNC"
echo "######################################"

echo "######################################"
echo "Developed by sspradhan.com"
echo "######################################"
echo "######################################"

echo "Loading"
echo "Done"


echo "######################################"
echo "System Updating"
echo "######################################"
# Update system
sudo apt-get update -y
echo "Done"

echo "######################################"
echo "Installing Requrements"
echo "######################################"
# All requirements
sudo apt-get install ubuntu-desktop apt-get gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal -y

echo "Done"

echo "######################################"
echo "Installing VNCServer"
echo "######################################"
# Install VNC Server
sudo apt-get install vnc4server -y

echo "Done"


echo "######################################"
echo "Starting VNCServer"
echo "######################################"
echo "######################################"
echo "It will ask you for password. Set any password you like"
echo "######################################"

# Starting VNC Server
vncserver :1

echo "Done"

echo "######################################"
echo "Killing VNCServer"
echo "######################################"

# Killing VNC Server
vncserver -kill :1

echo "Done"

echo "######################################"
echo "Prepairing your Desktop by Editing /.vnc/xstartup file"
echo "######################################"
# Edit Xstartup File
echo "#Additinal Added By sspradhan.com">>~/.vnc/xstartup
echo "gnome-panel &">>~/.vnc/xstartup
echo "gnome-settings-daemon &">>~/.vnc/xstartup
echo "metacity &">>~/.vnc/xstartup
echo "nautilus &">>~/.vnc/xstartup

echo "Done"

#Starting VNC Server
vncserver

echo "######################################"
echo "Installation Done"
echo "Important Thing To Remember"
echo "Your VNC accers id:" $ip":1"
echo "your Password: "$password
echo "To Stop VNCServer just type command: vncserver -kill :1"
echo "To start vncserver just use Command: vncserver"
echo "Every time after reboot or power on please start vncserver again"
echo ""
echo ""
echo "Thank you"
echo "Subhendu Sekhar Pradhan"
echo "https://www/sspradhan.com"
echo "######################################"
exit
