#!/bin/bash

echo "######################################"
echo "Ubuntu GUI Desktop Installer with VNC"
echo "######################################"

echo "######################################"
echo "Developed by sspradhan.com"
echo "Loading"
echo "########"
echo "###############"
echo "#####################"
echo "##########################"
echo "##############################"
echo "################################"
echo "#################################"
echo "######################################"
echo "Done"


echo "######################################"
echo "System Updating and Upgrading"
echo "######################################"
# Update system
sudo apt-get update && sudo apt-get upgrade -y

echo "Done"

echo "######################################"
echo "Installing Requrements"
echo "######################################"
# All requirements
sudo apt-get install ubuntu-desktop gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal

echo "Done"

echo "######################################"
echo "Installing VNCServer"
echo "######################################"
# Install VNC Server
sudo apt-get install vnc4server

echo "Done"


echo "######################################"
echo "Starting VNCServer"
echo "######################################"
echo "######################################"
echo "It will ask you for password. Set any password you like"
echo "######################################"

# Starting VNC Server
vncserver :1

echo "Done"

echo "######################################"
echo "Killing VNCServer"
echo "######################################"

# Killing VNC Server
vncserver -kill :1

echo "Done"

echo "######################################"
echo "Prepairing your Desktop by Editing /.vnc/xstartup file"
echo "######################################"
# Edit Xstartup File
echo "#Additinal Added By sspradhan.com">>~/.vnc/xstartup
echo "gnome-panel &">>~/.vnc/xstartup
echo "gnome-settings-daemon &">>~/.vnc/xstartup
echo "metacity &">>~/.vnc/xstartup
echo "nautilus &">>~/.vnc/xstartup

echo "Done"


echo "######################################"
echo "Installation Done"
echo "Important Thing To Remember"
echo "Now to Start VNCServer just type command: vncserver:1"
echo "To Stop VNCServer just type command: vncserver -kill :1"
echo "To Stop VNCServer just type command: vncserver -kill :1"
echo "Now you can access your desktop on Server through VNCserver:  YOURIPADRESS:1
echo "Your password you used to above while installing vncserver"
echo ""
echo ""
echo "Thank you"
echo "Subhendu Sekhar Pradhan"
echo "https://www/sspradhan.com"
echo "######################################"
exit
